Alinged the Hint in the box in fragment_send.xml
openMF/mobile-wallet pull request #1053
Opened 2020-11-16 06:45 UTC by ritish099

## Issue Fix
Fixes #1052

## Screenshots
![Screenshot_20201116-121228_Mifos Pay](https://user-images.githubusercontent.com/54978105/99220826-676bd600-2805-11eb-8e16-9229979fb0e6.jpg)

## Description
Now the hints are aligned inside the box

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-11-16 07:58 UTC, robustTechie commented
Hello @ritish099 here because of removing the text box padding the box appears to be too big can you just put the hint in the center instead of increasing box size :)

2020-11-16 08:02 UTC, robustTechie reviewed
Hello @ritish099 here because of removing the text box padding the box appears to be too big can you just put the hint in the center instead of increasing box size :)

2020-11-16 08:45 UTC, ritish099 commented
@robustTechie can we just make the height as "wrap content" instead of hardcoding the height. that would make it look good.
![Screenshot_20201116-141113_Mifos Pay](https://user-images.githubusercontent.com/54978105/99231030-10bac800-2816-11eb-94c4-f69ec166ac2e.jpg)

2020-11-16 09:24 UTC, robustTechie commented
Yeah you can do that, also you can try managing the padding inside the box.

2020-11-16 14:19 UTC, ritish099 commented
@robustTechie did wrap content. and it now look likes the previous image.

2020-11-16 14:24 UTC, robustTechie commented
Looks fine to me, can you squash all the commits to one ?

2020-11-16 14:37 UTC, ritish099 commented
@robustTechie Done

2020-11-16 16:45 UTC, robustTechie requested changes
LGTM

2020-11-16 19:12 UTC, shiv07tiwari reviewed
@ritish099 Nice job. Just a couple of things:-
1. Please add the latest screenshot (after your last commit)
2. Please wait for any of the maintainer's approval on the issue before creating a Pull Request in the future.

2020-11-17 04:30 UTC, ritish099 commented
Latest Screenshot after the last commit:
![error](https://user-images.githubusercontent.com/54978105/99346884-abb9ad80-28bb-11eb-93b8-4a43d676bd10.PNG)

2020-11-17 08:47 UTC, shiv07tiwari approved these changes

2020-11-17 08:56 UTC, merged