Adding noHistory=true in manifest of login activity
openMF/mobile-wallet pull request #1124
Opened 2021-01-06 11:29 UTC by Harshad09

## Issue Fix
Fixes #1122 

https://user-images.githubusercontent.com/50478348/103763580-0c55a300-5040-11eb-8aea-14b9e985affc.mp4

## Description
In manifest  in login activity made onHistory = true.

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2021-01-09 18:55 UTC, Harshad09 commented
@devansh-299  @s-ayush2903 Can you Please Review my PR

2021-01-09 19:27 UTC, devansh-299 requested changes

2021-01-09 19:27 UTC, devansh-299 commented on mifospay/src/main/AndroidManifest.xml
> +            android:noHistory="true" />
@Harshad09 I don't think it's a good idea to use `noHistory` as we are also creating intent to `MobileVerificationActivity` from this activity from which we may want to return.

Instead, you can probably have a workaround to handle the back press in passcode activity

2021-01-09 22:40 UTC, Harshad09 commented
@devansh-299  I have added 
API 16+ use: ```finishAffinity();```  Below API 16 use: ```ActivityCompat.finishAffinity(this);```  in the passcodeActivity

2022-08-06 09:39 UTC, devansh-299 commented
Closing this pull request (please see [link](https://github.com/openMF/mobile-wallet/issues/1122#issuecomment-1207183580) for reasoning)

2022-08-06 09:39 UTC, closed without merging