fix:#1156 Share and copy button moved adjacent to receipt title
openMF/mobile-wallet pull request #1157
Opened 2021-01-14 12:24 UTC by haran2248

## Issue Fix
Fixes #1156 
![WhatsApp Image 2021-01-14 at 17 47 50](https://user-images.githubusercontent.com/56928954/104590462-6209fb00-5691-11eb-8994-95632e63d7c1.jpeg)

## Screenshots

## Description

The share and copy buttons have been moved adjacent to the title of the unique receipt so that the download button doesnt cover it up.

##

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2021-01-14 12:35 UTC, haran2248 commented
@devansh-299  please review this

2021-01-15 08:37 UTC, devansh-299 commented
@haran2248 instead of moving the icons above, we can simply add a bottom margin equal/around the diameter of the fab to fix the convering up of buttons by fab on some devices

2021-01-15 11:41 UTC, haran2248 commented
![WhatsApp Image 2021-01-15 at 17 09 39](https://user-images.githubusercontent.com/56928954/104723048-a9a58b00-5754-11eb-989c-23b983897267.jpeg)
I have changed the margin of the fab,so that it doesnt affect the copy and share buttons

2021-01-27 06:47 UTC, devansh-299 commented
> 
> 
> ![WhatsApp Image 2021-01-15 at 17 09 39](https://user-images.githubusercontent.com/56928954/104723048-a9a58b00-5754-11eb-989c-23b983897267.jpeg)
> I have changed the margin of the fab,so that it doesnt affect the copy and share buttons

I meant adding bottom margin to the constraint layout containing the receipt link so that extra space at the bottom is available

2021-01-27 06:53 UTC, devansh-299 requested changes

2021-01-27 06:53 UTC, devansh-299 commented on mifospay/src/main/res/layout/activity_receipt.xml
> +        android:layout_marginBottom="@dimen/value_80sp"
Don't use `sp` for anything other than fonts. Sp stands for `Scalable pixels`, and these can vary (_be scaled_) as per the system font size preference of the user

2021-01-27 06:53 UTC, devansh-299 commented on mifospay/src/main/res/layout/activity_receipt.xml
> +        android:layout_marginRight="@dimen/value_12dp"
not needed, earlier `16dp` is fine

2021-01-27 06:53 UTC, devansh-299 commented on mifospay/src/main/res/values/dimens.xml
> +    <dimen name="value_5sp">5sp</dimen>
unnecessary addition, please remove this

2021-01-27 06:53 UTC, devansh-299 commented on mifospay/src/main/res/values/dimens.xml
> +    <dimen name="value_80sp">80sp</dimen>
remove this as also

2021-01-31 18:29 UTC, haran2248 commented
@devansh-299 please review this

2021-02-04 08:04 UTC, devansh-299 commented
> 
> 
> @devansh-299 please review this

Can you attach an updated screenshot, need to judge whether 80dp suitable or not

2021-02-04 08:11 UTC, devansh-299 commented
> 
> 
> > ![WhatsApp Image 2021-01-15 at 17 09 39](https://user-images.githubusercontent.com/56928954/104723048-a9a58b00-5754-11eb-989c-23b983897267.jpeg)
> > I have changed the margin of the fab,so that it doesnt affect the copy and share buttons
> 
> I meant adding bottom margin to the constraint layout containing the receipt link so that extra space at the bottom is available

Hey @haran2248 I guess you miss understood again, no problem but see we have a Constraint layout at _line 141_ so what I said was if we add a bottom margin to this layout, let's say 100dp then we will have 100dp of extra space at the bottom ensuring that fab doesn't always overlap the icons. 
Just try removing all the changes you made here and add some bottom margin to the constraint layout and you will get it

2021-02-04 20:29 UTC, haran2248 commented
![WhatsApp Image 2021-02-05 at 01 51 26](https://user-images.githubusercontent.com/56928954/106951345-ae5acf00-6755-11eb-9482-a35b631ef651.jpeg)
Is this ok @devansh-299 ?

2021-02-25 13:09 UTC, haran2248 commented
@devansh-299 Please check this

2022-02-10 06:07 UTC, merged