fix: updated the PR- feat : Implemented details on successful transaction
openMF/mobile-wallet pull request #1328
Opened 2022-04-11 10:22 UTC by alphaNewrex

## Issue Fix
Fixes merge issues in PR #428 
and Fixes Issue #425

## Description
Added a transaction receipt when a transaction is successful. this can be used to send the screenshot of the amount of money sent to anyone in order to confirm the money dispatched from our side.

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2022-04-11 10:59 UTC, alphaNewrex commented
@devansh-299 look into this PR and please review it.

2022-04-12 11:52 UTC, devansh-299 requested changes
Few more changes:
* Code formatting has several issues, just use _Control+Alt+L_ (Windows) or _Command+Option+L_ (MacOS) to reformat the code
* View  ids in the XML file are not meaningful. Follow [this article](https://medium.com/mindorks/android-resource-naming-convention-42e4e8026614) while naming views

2022-04-12 11:52 UTC, devansh-299 commented on mifospay/src/main/res/layout/fragment_make_transfer.xml
> +                android:layout_marginRight="@dimen/value_20dp"
To support possible use of RTL in future, better use `marginEnd` instead

2022-04-12 11:52 UTC, devansh-299 commented on mifospay/src/main/res/layout/fragment_make_transfer.xml
> +                android:layout_alignParentRight="true"
same here

2022-04-12 11:52 UTC, devansh-299 commented on mifospay/src/main/res/layout/fragment_make_transfer.xml
> +                android:visibility="visible"/>
space between `"` and `/>` is missing.

2022-04-12 11:52 UTC, devansh-299 commented on mifospay/src/main/res/layout/fragment_make_transfer.xml
> +                android:layout_toLeftOf="@id/view_transfer_success"
Same here, use `toStartOf` instead

2022-04-12 11:58 UTC, devansh-299 requested changes

2022-04-12 11:58 UTC, devansh-299 commented on mifospay/src/main/res/layout/fragment_make_transfer.xml
> +                android:id="@+id/payment_success"
View Id ideally should tell the use of the view, here it's not related to the its purpose

2022-04-12 11:58 UTC, devansh-299 commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/common/ui/MakeTransferFragment.java
> +    RelativeLayout relativeLayout;
Use `successLayout` as the variable name

2022-04-12 11:58 UTC, devansh-299 commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/common/ui/MakeTransferFragment.java
> +        Transaction transaction;
The variable declaration can be done in the same line as the assignment

2022-04-12 12:05 UTC, devansh-299 commented
> @devansh-299 look into this PR and please review it.

@alphaNewrex UI is not up to the mark, please make the following changes:
* The heading text should be changed to `Transaction Successful`
* The views should be arranged in the following verticle fashion: 
    1. Transaction ID as `Transaction Id: <transaction id>`
    2. The receiver as `Transferred To: <receiver name>`
    3. Amount as `Amount: <currency><amount>`

2022-04-12 12:12 UTC, devansh-299 requested changes

2022-04-12 12:12 UTC, devansh-299 commented on mifospay/src/main/res/layout/fragment_make_transfer.xml
> +                android:textColor="@color/primaryDarkBlue"
Button text won't be visible, use white instead

2022-04-12 12:12 UTC, devansh-299 commented on mifospay/src/main/res/layout/fragment_make_transfer.xml
> +                android:layout_marginTop="@dimen/value_10dp"
Increase the margin to 40dp

2022-04-12 12:12 UTC, devansh-299 commented on mifospay/src/main/res/layout/fragment_make_transfer.xml
> +            android:layout_height="match_parent"
Use `wrap_content` instead

2022-04-12 12:12 UTC, devansh-299 commented on mifospay/src/main/res/layout/fragment_make_transfer.xml
> +                android:layout_gravity="center"
No need for this

2022-04-12 12:12 UTC, devansh-299 commented on mifospay/src/main/res/layout/fragment_make_transfer.xml
> +                android:layout_marginTop="@dimen/value_20dp"
A better way of placing this will be to vertically centralize this view

2022-04-14 20:09 UTC, alphaNewrex commented
@devansh-299 I have updated the

 UI and made it Align Vertical. A sample for the same is attached below. Since the demo account credentials didn't have any transactions associated with them. I'm attaching a screenshot from Design Tab. The Text for each will be updated by the code.
![Screenshot 2022-04-15 013228](https://user-images.githubusercontent.com/77982973/163467589-1fe1e685-996d-40c5-85f4-5dee2a86518e.png )

2024-03-03 06:01 UTC, closed without merging