Fix: Not displaying all transactions on button click
openMF/mobile-wallet pull request #1517
Opened 2024-02-08 05:03 UTC by devrahul-2508

## Issue Fix
Fixes #1516 

## Screenshots

https://github.com/openMF/mobile-wallet/assets/91717339/91bd6120-b246-47d4-b63b-67d97bdfbfc4

## Description
Added an extra check if the filter type is "All" then display all credit and debit transactions

##

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2024-02-13 03:38 UTC, therajanmaurya requested changes

2024-02-13 03:38 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/presenter/HistoryPresenter.kt
> +        if(type!=null){
I think someone while migrating java to kotlin have made this nullable but this would not be nullabe, please remove and format and update the PR.

2024-02-19 18:24 UTC, devrahul-2508 commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/presenter/HistoryPresenter.kt
> +        if(type!=null){
@therajanmaurya I have updated the PR. Can u please check.

2024-02-26 02:59 UTC, therajanmaurya approved these changes

2024-02-26 02:59 UTC, merged