Refactor java class of domain client package to kotilin
openMF/mobile-wallet pull request #1541
Opened 2024-02-19 10:10 UTC by NiranjanNlc

## Issue Fix
Fixes #1529 partially 

## Screenshots

No change in UI 

## Description

##

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2024-02-19 17:53 UTC, therajanmaurya requested changes

2024-02-19 17:53 UTC, therajanmaurya commented on core/data/src/main/java/org/mifos/mobilewallet/core/data/fineract/entity/mapper/ClientDetailsMapper.kt
> +    //
Remove this comment

2024-02-19 17:53 UTC, therajanmaurya commented on core/model/src/main/java/com/mifos/mobilewallet/model/domain/client/Client.kt
> +data class Client(
Please implement using `Parcelable` annotation. This is not optimized code using convert java to kotlin.

2024-02-19 17:53 UTC, therajanmaurya commented on core/model/src/main/java/com/mifos/mobilewallet/model/domain/client/NewClient.kt
> +class NewClient(
I mentioned in the ticket, convert into data classes not classes.

2024-02-21 08:24 UTC, NiranjanNlc commented on core/data/src/main/java/org/mifos/mobilewallet/core/data/fineract/entity/mapper/ClientDetailsMapper.kt
> +    //
done

2024-02-21 08:56 UTC, closed without merging