refactor #1531: migrated payments screen to compose
openMF/mobile-wallet pull request #1548
Opened 2024-02-22 19:47 UTC by PratyushSingh07

## Issue Fix
Fixes #1531 

https://github.com/openMF/mobile-wallet/assets/90026952/b4fdfe38-dbfc-48cd-b62c-0d59c39a6869

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2024-03-18 05:14 UTC, PratyushSingh07 commented
@therajanmaurya in this PR, I have migrated the SendScreen and RequestScreen to compose in this PR.
However HistoryFragment, SIFragment are yet to be migrated. Can you please reivew this and merge it for the time being. Once merged I will fix the rest of the screens as well.

I am using HorizontalPager here so the rest of HistoryFragment and SIFragment will be blank for the time being.

2024-03-19 10:36 UTC, PratyushSingh07 commented
Please review this @therajanmaurya . I have migrated the payments screen to compose. Please review and merge this . Once merged I will look for any other bugs and edge cases that I might have missed

2024-03-22 21:11 UTC, therajanmaurya requested changes

2024-03-22 21:11 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/presenter/HistoryViewModel.kt
> +    data object EmptyList : HistoryUiState()
Empty

2024-03-22 21:11 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/presenter/HistoryViewModel.kt
> +    data class HistoryList(val list: List<Transaction>?) : HistoryUiState()
make it default empty and remove null

2024-03-22 21:11 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/ui/HistoryItem.kt
> +                    fontSize = 16.sp,
use typography

2024-03-22 21:11 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/ui/HistoryItem.kt
> +                    color = if (transactionType == TransactionType.CREDIT) Color(0xFF009688) else Color(0xFFF10606),
move to color

2024-03-22 21:11 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/ui/HistoryScreen.kt
> +fun HistoryScreen(
HistoryScreenContent

2024-03-22 21:11 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/PaymentsFragment.kt
> +    private fun searchContactClicked() {
Move this logic to compose

2024-03-22 21:11 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/PaymentsFragment.kt
> +        if (ContextCompat.checkSelfPermission(
move this permission to compose

2024-03-22 21:11 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/PaymentsScreen.kt
> +                2 -> HistoryScreen(historyViewModel.historyUiState.collectAsStateWithLifecycle().value)
name field and use

2024-03-22 21:11 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/PaymentsScreen.kt
> +                    standingInstructionViewModel.standingInstructionsUiState.collectAsStateWithLifecycle().value,
make field and use

2024-03-23 16:32 UTC, merged