refactor #1592: migrated edit profile screen to compose
openMF/mobile-wallet pull request #1595
Opened 2024-03-29 19:01 UTC by PratyushSingh07

## Issue Fix
Fixes #1592 

## Screenshots

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2024-03-30 18:28 UTC, therajanmaurya requested changes

2024-03-30 18:28 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/presenter/EditProfileViewModel.kt
> +        fetchProfileDetails()
Move this in Launchedeffect in EditProfileScreen

2024-03-30 18:28 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileScreen.kt
> +    EditProfileScreen(editProfileUiState = EditProfileUiState.Success(), {}, {}, {})
Add one more preview Success data

2024-03-30 21:21 UTC, therajanmaurya approved these changes

2024-03-30 21:21 UTC, merged

2024-05-08 18:05 UTC, AdityaKumdale commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.kt
> -    fun onSaveChangesClicked() {
onSaveChanges