refactor #1620: migrated notification screen to compose
openMF/mobile-wallet pull request #1621
Opened 2024-05-06 18:19 UTC by PratyushSingh07

## Issue Fix
Fixes #1620 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2024-05-06 19:26 UTC, AvneetSingh2001 requested changes

2024-05-06 19:26 UTC, AvneetSingh2001 commented on mifospay/src/main/java/org/mifospay/notification/presenter/NotificationViewModel.kt
> +    data object Empty : NotificationUiState
you can remove this empty state

2024-05-06 19:26 UTC, AvneetSingh2001 commented on mifospay/src/main/java/org/mifospay/notification/presenter/NotificationViewModel.kt
> +            _isRefreshing.emit(false)
move this to fetchNotification()

2024-05-06 19:26 UTC, AvneetSingh2001 commented on mifospay/src/main/java/org/mifospay/notification/ui/NotificationActivity.kt
> +//    }
remove commented code

2024-05-07 16:56 UTC, therajanmaurya requested changes

2024-05-07 16:56 UTC, therajanmaurya commented on gradle/libs.versions.toml
> +accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefreshVersion" }
It is depreciated https://google.github.io/accompanist/swiperefresh/ library

2024-05-07 16:56 UTC, therajanmaurya commented on gradle/libs.versions.toml
> +accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefreshVersion" }
This library is deprecated, with official pull refresh support in [androidx.compose.material.pullrefresh](https://developer.android.com/reference/kotlin/androidx/compose/material/pullrefresh/package-summary). The migration guide and original documentation is below.

2024-05-07 16:56 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifospay/notification/ui/NotificationScreen.kt
> +                        Column(
We have UI to show the empty data 
``` 
EmptyContentScreen(
                        modifier = Modifier,
                        title = stringResource(id = R.string.error_oops),
                        subTitle = stringResource(id = R.string.unexpected_error_subtitle),
                        iconTint = Color.Black,
                        iconImageVector = Icons.Rounded.Info
)
```

2024-05-07 16:56 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifospay/notification/ui/NotificationScreen.kt
> +                style = styleMedium16sp,
Use material theme `MaterialTheme.typography.bodySmall` 

`bodySmall` will be according to test styling. check in designsystem/MifosTypography which is perfect for the text

2024-05-07 16:56 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifospay/notification/ui/NotificationScreen.kt
> +@Preview(showSystemUi = true, showBackground = true)
Talk to @AvneetSingh2001 about the generating preview for different states and make change

2024-05-07 16:56 UTC, therajanmaurya requested changes

2024-05-07 16:56 UTC, therajanmaurya commented on gradle/libs.versions.toml
> +accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefreshVersion" }
Remove this

2024-05-08 16:48 UTC, therajanmaurya requested changes

2024-05-08 16:48 UTC, therajanmaurya commented on gradle/libs.versions.toml
> +accompanistSwiperefreshVersion = "0.27.0"
Remove this

2024-05-08 16:48 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifospay/notification/ui/NotificationScreen.kt
> +                            title = stringResource(id = R.string.error_oops),
Text is wrong, It should be something like 
title - Nothing to Notify
subtitle - There is nothing to show

2024-05-08 16:48 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifospay/notification/ui/NotificationScreen.kt
> +fun NotificationList(title: String, body: String, timestamp: String) {
change function name to `NotificationListItem`

2024-05-08 16:57 UTC, therajanmaurya approved these changes

2024-05-08 16:58 UTC, merged