refactor: showQr_migration_compose
openMF/mobile-wallet pull request #1633
Opened 2024-05-19 22:54 UTC by AvneetSingh2001

## Issue Fix
Fixes #1632 

Jira Task: [MW-25](https://mifosforge.jira.com/browse/MW-25)

## Screenshots

## Description
showQr Screen migration to compose

2024-05-25 17:35 UTC, PratyushSingh07 requested changes

2024-05-25 17:35 UTC, PratyushSingh07 commented on mifospay/src/main/java/org/mifospay/qr/showQr/presenter/ShowQrPresenter.kt
>      }
remove comments

2024-05-26 16:31 UTC, therajanmaurya requested changes

2024-05-26 16:31 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifospay/qr/showQr/presenter/ShowQrViewModel.kt
> +    val currency: String = "TZA",
make it usd

2024-05-26 16:31 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifospay/qr/showQr/ui/SetAmountDialog.kt
> +private fun validateInputs(
keep a flag value and maintain.

2024-05-26 16:31 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifospay/qr/showQr/ui/ShowQrActivity.kt
> +    private lateinit var qrDataString: String
Move it to viewmodel

2024-05-26 16:31 UTC, therajanmaurya commented on mifospay/src/main/java/org/mifospay/qr/showQr/ui/ShowQrScreen.kt
> +                currency = "TZA"
USD

2024-05-26 18:53 UTC, AvneetSingh2001 commented on mifospay/src/main/java/org/mifospay/qr/showQr/presenter/ShowQrPresenter.kt
>      }
done

2024-05-26 18:53 UTC, AvneetSingh2001 commented on mifospay/src/main/java/org/mifospay/qr/showQr/presenter/ShowQrViewModel.kt
> +    val currency: String = "TZA",
done

2024-05-26 18:53 UTC, AvneetSingh2001 commented on mifospay/src/main/java/org/mifospay/qr/showQr/ui/SetAmountDialog.kt
> +private fun validateInputs(
done

2024-05-26 18:53 UTC, AvneetSingh2001 commented on mifospay/src/main/java/org/mifospay/qr/showQr/ui/ShowQrActivity.kt
> +    private lateinit var qrDataString: String
done

2024-05-26 18:53 UTC, AvneetSingh2001 commented on mifospay/src/main/java/org/mifospay/qr/showQr/ui/ShowQrScreen.kt
> +                currency = "TZA"
done

2024-05-26 19:53 UTC, merged