New UI to change password
openMF/mobile-wallet pull request #1781
Opened 2024-10-04 22:08 UTC by rodrigosouzalopes94

## Issue Fix
Fixes #{Issue Number}
Jira Task: [MW145]https://mifosforge.jira.com/browse/MW-148

## Screenshots
![print_MW145](https://github.com/user-attachments/assets/f46f545d-e7a2-475f-8c26-66fd207f3ef1)

## Description
A new change password screen

##

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2024-10-05 05:14 UTC, niyajali requested changes

2024-10-05 05:14 UTC, niyajali commented on core/designsystem/src/main/kotlin/org/mifospay/core/designsystem/component/TextField.kt
> +            color = NewUi.primaryColor,
Can you format these lines of code.

2024-10-05 05:14 UTC, niyajali commented on core/designsystem/src/main/kotlin/org/mifospay/core/designsystem/component/TextField.kt
> +
Can you remove blank lines

2024-10-05 05:14 UTC, niyajali commented on core/designsystem/src/main/kotlin/org/mifospay/core/designsystem/component/TextField.kt
> +            disabledBorderColor = Color.Transparent, // Cor da borda quando desabilitado
And remove these comments too

2024-10-05 05:14 UTC, niyajali commented on core/designsystem/src/main/kotlin/org/mifospay/core/designsystem/component/TextField.kt
> +
Remove these extra blank lines..

2024-10-05 05:14 UTC, niyajali commented on feature/editpassword/src/main/kotlin/org/mifospay/feature/editpassword/EditPasswordScreen.kt
> +
Remove the blank lines

2024-10-05 05:14 UTC, niyajali commented on feature/editpassword/src/main/kotlin/org/mifospay/feature/editpassword/EditPasswordScreen.kt
> +
Remove here too

2024-10-05 05:17 UTC, niyajali commented
Run `ci-prepush.sh` bash script before commiting or pushing your changes it will format and check for any errors

2024-10-05 05:19 UTC, niyajali commented
Can you upload both Old UI and Updated UI Image

2024-10-05 14:01 UTC, rodrigosouzalopes94 commented on core/designsystem/src/main/kotlin/org/mifospay/core/designsystem/component/TextField.kt
> +            color = NewUi.primaryColor,
I already change

2024-10-05 14:01 UTC, rodrigosouzalopes94 commented on core/designsystem/src/main/kotlin/org/mifospay/core/designsystem/component/TextField.kt
> +
Done

2024-10-05 14:01 UTC, rodrigosouzalopes94 commented on core/designsystem/src/main/kotlin/org/mifospay/core/designsystem/component/TextField.kt
> +            disabledBorderColor = Color.Transparent, // Cor da borda quando desabilitado
Done

2024-10-05 14:01 UTC, rodrigosouzalopes94 commented on core/designsystem/src/main/kotlin/org/mifospay/core/designsystem/component/TextField.kt
> +
Done

2024-10-05 14:02 UTC, rodrigosouzalopes94 commented on feature/editpassword/src/main/kotlin/org/mifospay/feature/editpassword/EditPasswordScreen.kt
> +
Done

2024-10-05 14:10 UTC, niyajali commented
Commit your changes, i didn't see any

2024-10-05 15:20 UTC, niyajali requested changes

2024-10-05 15:20 UTC, niyajali commented on git
Remove this file

2024-10-05 15:46 UTC, rodrigosouzalopes94 commented on git
Done

2024-10-07 12:38 UTC, niyajali commented
@rodrigosouzalopes94 fix this build error

> Task :core:designsystem:compileDemoDebugKotlin FAILED
e: file:///home/runner/work/mobile-wallet/mobile-wallet/core/designsystem/src/main/kotlin/org/mifospay/core/designsystem/component/TextField.kt:119:25 Unresolved reference 'NewUi'.

2024-10-07 16:30 UTC, itsPronay requested changes
Hello @rodrigosouzalopes94 , thanks for the PR but You modified the old `OutlinedTextField` and set colors to `color.Transparent`. We won't be using that anymore. 

Take reference from finance/payment/editProfile screen. also after you are done please attach the figma UI as well

2024-10-07 21:39 UTC, rodrigosouzalopes94 commented
> Hello @rodrigosouzalopes94 , thanks for the PR but You modified the old `OutlinedTextField` and set colors to `color.Transparent`. We won't be using that anymore.
> 
> Take reference from finance/payment/editProfile screen. also after you are done please attach the figma UI as well

Can you help to make the clean code about these styles?

2024-10-08 10:57 UTC, itsPronay commented
> Can you help to make the clean code about these styles?

it's not about styles, You need to modify `MifosTextField` that we already have in `textfield.kt` file.
 If you still have any doubts feel free to let me know on Slack.

2024-10-09 09:22 UTC, rodrigosouzalopes94 commented
Done.

2024-10-09 11:48 UTC, itsPronay commented
> Done.

1. please update the new UI in your commit message. also, add Figma UI as well
2. fix conflicts
3. Please squash your commits as well (squash before pull the remote changes) 
![image](https://github.com/user-attachments/assets/11daabb9-a89b-4961-b603-08e870581f13)

2024-10-09 22:11 UTC, rodrigosouzalopes94 commented
Figma UI
![image](https://github.com/user-attachments/assets/aaeef135-0b60-46e9-99b0-a1c40b9e1d5a)
New Screen
![newUI](https://github.com/user-attachments/assets/db1680a8-b99f-4b91-8648-59be47f09d15)

2024-10-09 22:15 UTC, rodrigosouzalopes94 reviewed
Fixed the conflits

2024-10-10 13:48 UTC, niyajali commented
@rodrigosouzalopes94 As I can see, the trailing icon color doesn't match the color as per Figma UI

2024-10-10 20:10 UTC, rodrigosouzalopes94 commented
I gonna fixed.

2024-10-11 14:17 UTC, niyajali commented
@rodrigosouzalopes94 take a look into this pr #1787 , might helps

2024-10-18 03:20 UTC, therajanmaurya commented
@niyajali can you help @rodrigosouzalopes94 so we can merge this PR

2024-10-18 08:33 UTC, niyajali commented
@rodrigosouzalopes94 Here is the pr #1787 of this module

2025-01-30 04:19 UTC, therajanmaurya commented
Already Implemented

2025-01-30 04:19 UTC, closed without merging