fix : Limit of digits of Credit Card Number while adding a Card
openMF/mobile-wallet pull request #421
Opened 2019-03-06 13:06 UTC by RajaVamsi11

Fixes #420 

**Summary**
Added validation checker and limited the digits length of Credit Card Number in Saved Cards.
![screenshot_2019-03-06-18-17-12-189_org mifos mobilewallet mifospay](https://user-images.githubusercontent.com/30550059/53883322-a7dded00-403e-11e9-926f-c3f11e4414a9.png)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2019-03-06 14:16 UTC, naman14 commented
@RajaVamsi11 
Why not use the credit card number verification method already present in `CardsPresenter`?
https://github.com/openMF/mobile-wallet/blob/a33c849d69fbd3e8f3d2ae2d9d18d64a130e1d74/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/presenter/CardsPresenter.java#L195

Also, credit cards can have as many as 19 digits, there's no need to limit the number of digits. Rather use the credit card verification algorithm mentioned above.

2019-03-06 15:20 UTC, RajaVamsi11 commented
@naman14 
   
        int u = 2;
        if (u - 2 == 0) {
            return true; // for backend testing. remove after testing.
        }
According to the above code in the ValidateCreditCardNumberMethod() it always return true. It must be removed. Can I remove it as it says it is for backend testing, remove after testing.

2019-03-06 15:48 UTC, RajaVamsi11 commented
@naman14 Updated according to the changes requested. Can you please review once?

2019-12-05 10:11 UTC, luckyman20 requested changes

2019-12-05 10:11 UTC, luckyman20 commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/savedcards/ui/AddCardDialog.java
> +            Toaster.showToast(getContext(), getString(R.string.enter_valid_card_number));
@RajaVamsi11 Use Snackbar instead.

2024-01-14 19:54 UTC, closed without merging