fix: confirmation dialogBox for Delete Bank
openMF/mobile-wallet pull request #681
Opened 2020-01-26 18:36 UTC by laxyapahuja

## Issue Fix
Fixes #456 

## Screenshots
<img src="https://user-images.githubusercontent.com/31318248/73139890-c9055d00-4098-11ea-8489-46061e7a4966.png" width=300/>

## Description
I've added a confirmation Dialog Box for Delete Bank using the ```DialogBox``` util class.

##
- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-01-26 18:51 UTC, rachittt commented
the dialog message "this will delete the selected bank." seems unnecessary in this case.

2020-01-26 18:53 UTC, laxyapahuja commented
> the dialog message "this will delete the selected bank." seems unnecessary in this case.

The DialogBox class has a message as a necessity. I can update it to accept null values. Thoughts? @luckyman20

2020-01-29 15:06 UTC, luckyman20 commented
@laxyapahuja I think there can be one more constructor which doesn't requires `message`.

2020-05-19 17:39 UTC, rachittt commented
@laxyapahuja can you please update the PR and remove the dialogBox message.

2020-05-19 17:39 UTC, rchtgpt requested changes
@laxyapahuja please remove the dialogBox message.

2020-05-19 17:51 UTC, s-ayush2903 commented
Just a suggestion: It would be better if we have something like generic dialog box and use it wherever needed rather creating a fresh one all the time

2020-05-19 18:59 UTC, rachittt commented
@s-ayush2903, we have it already. 

@laxyapahuja please use it. [this](https://github.com/openMF/mobile-wallet/blob/dev/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/DialogBox.java) might help you.

2020-05-21 13:19 UTC, rachittt commented
@laxyapahuja if we don't get a response within 2 days, we will have to close this PR because it is restricting other contributors from working on it.

2020-05-25 11:20 UTC, closed without merging