Fix 800 - added cancel button in ShowQrActivity
openMF/mobile-wallet pull request #801
Opened 2020-03-08 18:41 UTC by dubeyaayush07

Fix #800

![Screenrecorder-2020-03-09-00-04](https://user-images.githubusercontent.com/30518564/76169015-82784780-619a-11ea-82a6-76c99cfbd21a.gif)

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-05-15 19:01 UTC, devansh-299 requested changes

2020-05-15 19:01 UTC, devansh-299 commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java
> +        editTextDialog.setNegativeButton("Cancel", new DialogInterface.OnClickListener() {
@dubeyaayush07 please use "Cancel" string from the `strings.xml` file

2020-05-17 07:38 UTC, rchtgpt requested changes
hello @dubeyaayush07, can you please use "Cancel" string from the `strings.xml` file as pointed out by @devansh-299 ?

2020-05-20 11:57 UTC, rachittt commented
Closing this because of inactivity.

2020-05-20 12:10 UTC, dubeyaayush07 commented
@rachittt Sorry for the delay I was busy with some other work. If you want I can still make the requested changes

2020-05-20 12:11 UTC, rachittt commented
@dubeyaayush07 please make the changes.

2020-05-20 12:49 UTC, dubeyaayush07 commented
@rachittt  done

2020-05-20 12:52 UTC, devansh-299 commented
> @rachittt done

thanks @dubeyaayush07

2020-05-20 12:52 UTC, devansh-299 approved these changes

2020-05-20 13:05 UTC, rchtgpt approved these changes
thanks @dubeyaayush07

2020-05-20 13:06 UTC, merged