fix#661 - added updated screenshots of the entire app
openMF/mobile-wallet pull request #950
Opened 2020-05-22 06:33 UTC by devansh-299

## Issue Fix
Fixes #661 

## Description
Updated the screenshots and added a link to `Screenshot.md` in `README.md`

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-05-22 06:34 UTC, devansh-299 commented
@rachittt please have a look

2020-05-23 16:06 UTC, Bhavnaharitsa commented on Screenshot.md
> +<img src="https://user-images.githubusercontent.com/46667021/82584793-a13f8500-9bb2-11ea-847d-bb0e05279309.jpg" width="288" height="500" />
Amazing organization of images. However, I feel the Markdown way is better. It helps you to organize images in tables, give a description for every image. You can refer to this: https://gist.github.com/grocky/5d75af69b4f4c10304bf. and also avoids the hardcoded way, which might differ when the orientation changes and the screen size changes. You might choose to ignore it as well :).

2020-05-23 19:01 UTC, luckyman20 commented
I would suggest adding labels and spacing to screenshots. @devansh-299

2020-05-23 20:07 UTC, devansh-299 commented
@Bhavnaharitsa thank you for the suggestion, I will update the PR accordingly. 
@luckyman20 should I label screens as for example - `Send Fragment` or by describing the process like "Making a Payment"

2020-05-24 06:15 UTC, luckyman20 commented
@devansh-299 well, you can do something like 'sending a payment' or 'transfer money screen' as it could be understood by both developers and users.

2020-05-25 10:50 UTC, rachittt commented on Screenshot.md
> +|Payment Screen|Scanning QR Code for VPA Address|Making a Payment|
```suggestion
|Selecting Transfer Method|Scanning QR Code for VPA Address|Making a Payment|
```

2020-05-25 10:52 UTC, rchtgpt requested changes

2020-05-25 10:52 UTC, rachittt commented on Screenshot.md
> +|Payment Screen|Scanning QR Code for VPA Address|Making a Payment|
```suggestion
|Selecting Transfer Method|Scanning QR Code for VPA Address|Making a Payment|
```

2020-05-25 10:52 UTC, rachittt commented on Screenshot.md
> +|Bank Accounts Screen|Linking New Account|Phone Number Verification|
```suggestion
|Bank Accounts Screen|Link New Bank Account|Phone Number Verification|
```

2020-05-25 10:52 UTC, rachittt commented on Screenshot.md
> +|Edit Profile Screen|Change Password Screen|Changing Passcode|
```suggestion
|Edit Profile Screen|Change Password Screen|Change Passcode Screen|
```

2020-05-25 11:18 UTC, merged