refactor: Converted Utils Class to Kotlin Object
openMF/mobile-wallet pull request #952
Opened 2020-05-22 07:11 UTC by s-ayush2903

## Issue Fix
Fixes #922 

## Screenshots

NA
## Description

Converted the concerned file to kt Object and made desired changes in the corresponding files
##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-05-22 09:51 UTC, jawidMuhammadi commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/auth/ui/LoginActivity.java
> +        Utils.INSTANCE.hideSoftKeyboard(this);
Do we really need `INSTANCE` here and in other files, can't we call the method directly like: `Utils.hideSoftKeyboard(this);`?

2020-05-22 12:42 UTC, s-ayush2903 commented
As of now, No. One can't refer a non static method from a static context.
So each and every time, to use that, one'll have to create an instance of
same.
But, there must be some better way of it, rather repeating lines, lemme go
through kt docs, I'll update if possible.

On Fri, May 22, 2020, 3:22 PM AhmadJawid <notifications@github.com> wrote:

> *@jawidMuhammadi* commented on this pull request.
> ------------------------------
>
> In
> mifospay/src/main/java/org/mifos/mobilewallet/mifospay/auth/ui/LoginActivity.java
> <https://github.com/openMF/mobile-wallet/pull/952#discussion_r429152715>:
>
> > @@ -101,7 +101,7 @@ private void handleLoginInputChanged() {
>
>      @OnClick(R.id.btn_login)
>      public void onLoginClicked() {
> -        Utils.hideSoftKeyboard(this);
> +        Utils.INSTANCE.hideSoftKeyboard(this);
>
> Do we really need INSTANCE here and in other files, can't we call the
> method directly like: Utils.hideSoftKeyboard(this);?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openMF/mobile-wallet/pull/952#pullrequestreview-416788018>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANPP257A6LJILDIWZFH7X3LRSZDMXANCNFSM4NHRPCRQ>
> .
>

2020-05-22 13:06 UTC, s-ayush2903 commented
Maximum effort is made to keep this PR as semantic as possible(refraining from making changes in other files), so for that, methods have been annotated as static in the kt object file. Which works well and fine now, but as soon as the files(having implementation of those methods/using those methods) are in kt, then static annotations from those functions will also have to be removed(only to kill redundancy)

2020-05-22 14:31 UTC, jawidMuhammadi approved these changes
LGTM :)

2020-05-23 19:15 UTC, s-ayush2903 commented
Please Review

On Fri, May 22, 2020, 8:02 PM AhmadJawid <notifications@github.com> wrote:

> *@jawidMuhammadi* approved this pull request.
>
> LGTM :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openMF/mobile-wallet/pull/952#pullrequestreview-416957795>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANPP25ZVRCUIKP5TZ27W2RDRS2EFXANCNFSM4NHRPCRQ>
> .
>

2020-05-25 12:43 UTC, s-ayush2903 commented
> Please Review

@rachittt @luckyman20 Please look into it and review

2020-05-28 14:13 UTC, shiv07tiwari requested changes

2020-05-28 14:13 UTC, shiv07tiwari commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Utils.kt
> +        val imm =
Just rename this variable imm to it's elaborate camel case form. Rest looks good.

2020-05-28 22:50 UTC, shiv07tiwari approved these changes

2020-05-28 22:51 UTC, merged