Add Passcode verification for editing user credential
openMF/mobile-wallet pull request #971
Opened 2020-06-01 21:11 UTC by refactor-droidyy

## Issue Fix
Fixes #853 

## Screenshots

![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/44283521/83454922-902c2900-a47a-11ea-8890-33391211e3ac.gif)

## Description

Added passcode verification for user editing user credentials.

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

2020-06-02 12:40 UTC, refactor-droidyy commented
@shiv07tiwari please review

2020-06-03 07:26 UTC, devansh-299 requested changes
@refactor-droidyy currently in your implementation there's a by-pass to this security check. Tap on User Profile Image, and you are in `EditProfileActivity` without any passcode verification.
Thank you for fixing the crashing issue as mentioned [here](https://github.com/openMF/mobile-wallet/pull/854#pullrequestreview-413368584) but I still don't think user should be directly logged out on failing. @shiv07tiwari @luckyman20 what are your views. Also "Forgot Password, Login Manually" issue still persists,to overcome these I think we may need to override the methods as done [here](https://github.com/openMF/mobile-wallet/pull/684), this is not the best way but its the only work around that I could find

2020-06-03 07:26 UTC, devansh-299 commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/ProfileFragment.java
>              getActivity().startActivity(new Intent(getActivity(), EditProfileActivity.class));
There's no need for this line as later you are already creating an intent `PassCodeActivity` the very next line

2020-06-04 16:15 UTC, refactor-droidyy commented on mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/ProfileFragment.java
>              getActivity().startActivity(new Intent(getActivity(), EditProfileActivity.class));
@devansh-299 I think this behaviour of user logging out if the passcode entered is incorrect 3 times it would be good for the user account security

2020-06-07 19:46 UTC, luckyman20 commented
Yeah, I agree with @devansh-299

It could be something like if you enter wrong passcode for 3 times then you're logged out.

2020-06-07 19:50 UTC, refactor-droidyy commented
> Yeah, I agree with @devansh-299
> 
> It could be something like if you enter wrong passcode for 3 times then you're logged out.

@luckyman20 this PR has the above implementation that if you enter wrong passcode for 3 times then you're logged out.

2020-06-07 19:52 UTC, luckyman20 commented
In that case, @devansh-299 do you have anything else in mind which might suit better to this use case?

2020-06-07 20:07 UTC, devansh-299 commented
> In that case, @devansh-299 do you have anything else in mind which might suit better to this use case?

No, I was just doubtful whether this functionality should be added or not.

2024-03-03 06:03 UTC, therajanmaurya commented
Unrelated and not needed anymore

2024-03-03 06:03 UTC, closed without merging